# 主要内容
常量
变量
占位符
张量

# 张量(tensor)
张量是对矢量和矩阵向潜在的更高维度的泛化。TensorFlow 在内部将张量表示为基本数据类型的 n 维数组。
tf.Tensor 具有以下属性：

- 数据类型（例如 float32、int32 或 string）
- 形状  

张量中的每个元素都具有相同的数据类型，且该数据类型一定是已知的。形状，即张量的维数和每个维度的大小，可能只有部分已知。如果其输入的形状也完全已知，则大多数操作会生成形状完全已知的张量，但在某些情况下，只能在执行图时获得张量的形状。

张量的类型：
- tf.Variable
- tf.constant
- tf.placeholder
- tf.SparseTensor
- tf.TensorArray

In [3]:
from __future__ import print_function
import tensorflow as tf

print(tf.__version__)

2.0.0-alpha0


## 阶
tf.Tensor 对象的阶是它本身的维数

如下表所示，TensorFlow 中的每个阶都对应一个不同的数学实例：

|阶|	数学实例|
|---|---| 
|0|	标量（只有大小）|
|1|	矢量（大小和方向）|
|2|	矩阵（数据表）|
|3|	3 阶张量（数据立体）|
|n|	n 阶张量（自行想象）|

### 0阶

In [4]:
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

In [10]:
mammal.shape, ignition.shape, floating.shape

(TensorShape([]), TensorShape([]), TensorShape([]))

### 1 阶
要创建 1 阶 tf.Tensor 对象，可以通过传递一个项目列表作为初始值

In [11]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

mystr.shape, cool_numbers.shape, first_primes.shape, its_very_complicated.shape

(TensorShape([1]), TensorShape([2]), TensorShape([5]), TensorShape([2]))

### 高阶

2 阶 tf.Tensor 对象至少包含一行和一列：

In [12]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

mymat.shape, myxor.shape, linear_squares.shape, rank_of_squares.shape, mymatC.shape

(TensorShape([2, 1]),
 TensorShape([2, 2]),
 TensorShape([4, 1]),
 TensorShape([]),
 TensorShape([2, 1]))

更高阶的张量由一个 n 维数组组成。例如，在图像处理过程中，会使用许多 4 阶张量，维度对应批次大小、图像宽度、图像高度和颜色通道。

In [16]:
my_image = tf.zeros([10, 299, 299, 3])  # batch x height x width x color

my_image.shape

TensorShape([10, 299, 299, 3])

### 获取 tf.Tensor 对象的阶

In [21]:
r = tf.rank(my_image)

print(r)
print('阶：', r.numpy())


tf.Tensor(4, shape=(), dtype=int32)
阶： 4


### tf.Tensor 对象的形状·
张量的形状是每个维度中元素的数量。TensorFlow 在图的构建过程中自动推理形状。这些推理的形状可能具有已知或未知的阶。如果阶已知，则每个维度的大小可能已知或未知。

阶，形状和维数关系如下：

| 阶   | 维数 | 形状               | 示例                               |
| ---- | ---- | ------------------ | ---------------------------------- |
| 0    | 0-D  | []                 | 0 维张量。标量。                   |
| 1    | 1-D  | [D0]               | 形状为 [5] 的 1 维张量。           |
| 2    | 2-D  | [D0, D1]           | 形状为 [3, 4] 的 2 维张量。        |
| 3    | 3-D  | [D0, D1, D2]       | 形状为 [1, 4, 3] 的 3 维张量。     |
| n    | n 维 | [D0, D1, ... Dn-1] | 形状为 [D0, D1, ... Dn-1] 的张量。 |


形状可以通过整型 Python 列表/元组或者 tf.TensorShape 表示。
可以通过两种方法获取 tf.Tensor 的形状：
- 查看tf.Tensor 对象的shape属性
- tf.shape

In [34]:
my_image.shape, tf.shape(my_image)

(TensorShape([10, 299, 299, 3]),
 <tf.Tensor: id=168, shape=(4,), dtype=int32, numpy=array([ 10, 299, 299,   3], dtype=int32)>)

### 改变tf.Tensor对象的形状
张量的元素数量是其所有形状大小的乘积。标量的元素数量永远是 1。由于通常有许多不同的形状具有相同数量的元素，因此如果能够改变 tf.Tensor 的形状并使其元素固定不变通常会很方便

In [38]:
rank_three_tensor = tf.ones([2, 3, 4])
rank_three_tensor.numpy()

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [39]:
tf.reshape(rank_three_tensor, [2, 12])

<tf.Tensor: id=189, shape=(2, 12), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [40]:
tf.reshape(rank_three_tensor, [3, -1])

<tf.Tensor: id=192, shape=(3, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [41]:
tf.reshape(rank_three_tensor, [-1, 4])

<tf.Tensor: id=195, shape=(6, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [42]:
tf.reshape(rank_three_tensor, [-1,2,3])

<tf.Tensor: id=198, shape=(4, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

### tf.Tensor对象的数据类型
通过Tensor.dtype 属性查看tf.Tensor对象的数据类型。
一个 tf.Tensor 只能有一种数据类型。但是，可以将任意数据结构序列化为 string 并将其存储在 tf.Tensor 中。

可以通过 tf.cast将 tf.Tensor 从一种数据类型转型为另一种

用 python 对象创建 tf.Tensor 时，可以选择指定数据类型。如果不指定数据类型，TensorFlow 会选择一个可以表示您的数据的数据类型。TensorFlow 会将 Python 整数转型为 tf.int32，并将 python 浮点数转型为 tf.float32。此外，TensorFlow 使用 Numpy 在转换至数组时使用的相同规则。

In [46]:
int_tensor = tf.constant([1, 2, 3])
float_tensor = tf.cast(int_tensor, dtype=tf.float32)
int_tensor.dtype, float_tensor.dtype

(tf.int32, tf.float32)

### tf.Tensor 切片
由于 tf.Tensor 是 n 维单元数组，可以通过数组切片的方式来访问张量中的元素。
- 0 阶张量（标量）不需要索引，因为其本身便是单一数字。
- 对于 1 阶张量（矢量），可以通过传递一个索引访问某个数字。
- 对于 2 阶 tf.Tensor，传递两个数字会如预期般返回一个标量，而传递一个数字则会返回一个矩阵子矢量。
- 更高阶的张量来说很有用，可以帮助访问其子矢量，子矩阵，甚至其他子张量。

In [23]:
squarish_squares

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>

In [26]:
squarish_squares[1].numpy()

array([16, 25], dtype=int32)

In [28]:
squarish_squares[0,1].numpy()

9

In [30]:
squarish_squares[:,1].numpy()

array([ 9, 25], dtype=int32)

In [48]:
constant = tf.constant([1, 2, 3])
tensor = constant * constant
print(tensor.numpy())

[1 4 9]


In [50]:
tf.print(tensor)

[1 4 9]


# 常量(constant)
- 常量的定义
- 常量的基本操作

In [2]:
# 定义张量常量
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

## 常量基本元素运算

In [3]:
# 张量常量的基本操作，有两种方式：1）基于函数，2）基于数学操作符

add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

add1 = a + b

# 获取运算的结果
print('add = ', add.numpy())
print('sub = ', sub.numpy())
print('mul = ', mul.numpy())
print('div = ', div.numpy())

print('add1 = ', add1.numpy())



add =  5
sub =  -1
mul =  6
div =  0.6666666666666666
add1 =  5


## 常量列表运算

In [4]:
# 求mean、sum、max、min、连乘等
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])
max = tf.reduce_max([[a, b, c]])

prod = tf.reduce_prod([a, b, c])
all = tf.reduce_all([a, b, c])

print('mean = ', mean.numpy())
print('sum = ', sum.numpy())
print('max = ', max.numpy())
print('prod = ', prod.numpy())
print('all = ', all.numpy())


mean =  3
sum =  10
max =  5
prod =  30
all =  True


## 常量矩阵运算

In [5]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

product

<tf.Tensor: id=62, shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [6]:
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)

# 占位符(placeholder)
占位符表示承诺在稍后提供值，它就像函数参数。

In [ ]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
